openapi: 3.0.0
info:
  title: APIS
  version: 1.0.0
paths:
  /user:
    post:
      summary: Create user
      description: Create user by request body
      tags:
      - User 
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                email:
                  type: string 
                name:
                  type: string
                password: 
                  type: string
                phone:
                  type: string
      responses:
        "201":
          description: User Created
        "400":
          description: Bad user request

